defaults:
  - train_residual_openpi_right_arm
  - _self_

residual:
  alpha: 0.01

offline:
  prepared_path: /home/hello/codebase/serl_torch/examples/agibot_real/outputs/offline_data/office_setting/openpi_pi05_task_3463_3540_mouse_only_right_hand_camera_position_15hz_chunk15_alpha0p01
  prepare:
    output_root: /home/hello/codebase/serl_torch/examples/agibot_real/outputs/offline_data
