 # @package _global_
defaults:
  - /exp1/train_residual_task9_exp1_scripts_2@_global_
  - _self_

runtime:
  trainer_port: 50054
  broadcast_port: 50055
  trainer_transport:
    data_port: 50056

wandb:
  exp_name: ${task.suite_name}_task_${task.task_id}_exp1_chunk_local_no_offline

policy:
  port: 50051

backfill_policy:
  port: 50052

env:
  remote:
    port: 50050

offline:
  enabled: false
  prepared_path: null
  ratio: 0.0
  pretrain_steps: 0

training:
  async_eval:
    env:
      remote:
        port: 50053

launch:
  output_root: outputs/exp1/${task.suite_name}_task${task.task_id}/chunk_local_no_offline
