defaults:
  - train_pld_task4_m06_boot50_w100_xi05
  - _self_

openpi:
  port: 32804

env:
  remote:
    port: 31804

training:
  max_online_env_steps: 300000
  warmup_base_episodes: 100
  warmup_base_steps: 0
  warmup_separate: true
  enable_base_probing: false
  probing_alpha: null
  probing_min_steps: 0
  probing_max_steps: 0
  async:
    enabled: true
    update_frequency: 20
    idle_sleep_sec: 0.002
  xi_scheduler:
    enabled: true
    type: linear
    min_xi: 0.05
    warmup_steps: 0
    anneal_steps: 90000
  async_eval:
    enabled: true
    env_port: 31904

hydra:
  run:
    dir: outputs/libero/pld_matrix/task4/m06_boot50_w100_xi05_sched300k/${now:%Y-%m-%d}/${now:%H-%M-%S}
