defaults:
  - train_residual_sac
  - _self_

residual:
  xi: 0.25

openpi:
  port: 32004

env:
  remote:
    port: 31004

offline:
  symmetric_replay: false
  ratio: 0.25

sac:
  utd_ratio: 4

training:
  training_starts: 1000
  max_online_env_steps: 300000
  calql_pretrain:
    enabled: false

hydra:
  run:
    dir: outputs/libero/train_residual_sac_xi025_mix25_calql_off_utd4_start1000/${now:%Y-%m-%d}/${now:%H-%M-%S}
