defaults:
  - train_residual_sac
  - _self_

residual:
  xi: 0.75
  action_dim: 6
  control_gripper: false

openpi:
  port: 32106

env:
  remote:
    port: 31106

offline:
  symmetric_replay: true
  ratio: 0.5

sac:
  utd_ratio: 2

training:
  warmup_base_episodes: 0
  training_starts: 200
  max_online_env_steps: 300000
  calql_pretrain:
    enabled: true
    steps: 2000
    batch_size: 128
    alpha: 1.0
    n_actions: 10
    temperature: 1.0

hydra:
  run:
    dir: outputs/libero/train_residual_sac_xi075_v2_stable_armonly/${now:%Y-%m-%d}/${now:%H-%M-%S}
